spring.application.name=NewPathBackEnd

spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=https://nickgraysenko.org/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.publishable-key=${STRIPE_PUBLIC_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.lifetime: 20d
jwt.refreshlifetime: 40d
